<template><NexaLayout><main id="main-content" class="wrap changes-main"><section class="page-intro"><p class="eyebrow">PCL Nexa</p><h1>{{ en ? 'What’s new.' : '每一步，都有记录。' }}</h1><p>{{ en ? 'Release notes for Nexa 2.0.' : 'Nexa 2.0 的版本更新与改进。' }}</p></section><div class="changes-toolbar"><router-link to="/download">‹ {{ en ? 'Downloads' : '返回下载' }}</router-link><a :href="NEXA_GITHUB + '/releases'" target="_blank" rel="noreferrer">GitHub Releases ↗</a></div><p v-if="loading" class="load-message" role="status">{{ en ? 'Loading release notes…' : '正在读取更新日志…' }}</p><p v-else-if="!releases.length" class="load-message" role="status">{{ en ? 'Release notes are unavailable here. View them on GitHub.' : '暂时无法读取更新日志，请前往 GitHub 查看。' }}</p><article v-for="release in releases" :key="release.tag_name" class="release-entry"><header><span class="alpha-badge">{{ nexaChannel(release.tag_name)?.toUpperCase() }}</span><h2>{{ release.tag_name.replace(/^v/,'') }}</h2><time :datetime="release.published_at">{{ formatDate(release.published_at) }}</time><a :href="release.html_url" target="_blank" rel="noreferrer">{{ en ? 'View on GitHub' : '在 GitHub 查看' }} ↗</a></header><div class="release-body"><p class="release-source">{{ en ? 'From the project’s published release notes. Original language retained.' : '以下为项目发布的原始更新记录。' }}</p><p v-if="!release.body">{{ en ? 'No release notes were provided for this version.' : '此版本未提供更新说明。' }}</p><div v-for="(line,index) in notes(release.body)" :key="index" :class="line.kind">{{ line.text }}</div></div></article></main></NexaLayout></template>
<script setup lang="ts">
import { computed, onMounted, onBeforeUnmount, ref, watchEffect } from 'vue';
import { useI18n } from 'vue-i18n';
import NexaLayout from '@/components/market/NexaLayout.vue';
import { NEXA_GITHUB, loadNexaReleases, nexaChannel, type NexaRelease } from '@/utils/nexaReleases';
import { applyPageSeo } from '@/utils/seo';
const { locale } = useI18n(); const en = computed(()=>locale.value!=='zh');
const releases=ref<NexaRelease[]>([]); const loading=ref(true); const controller=new AbortController();
onMounted(async()=>{try {releases.value=await loadNexaReleases(controller.signal);} catch {releases.value=[];} finally {loading.value=false;}});
onBeforeUnmount(()=>controller.abort());
const formatDate=(date:string)=>new Intl.DateTimeFormat(en.value?'en':'zh-CN',{year:'numeric',month:'long',day:'numeric'}).format(new Date(date));
function notes(body:string) { const start=body.search(/^## (更新内容|更新日志|Changes|Changelog|What's Changed)/mi); const content=start>=0?body.slice(start):body; return content.split('\n').filter(l=>l.trim()).map(line=>({kind:line.startsWith('#')?'note-heading':/^\s*[-*] /.test(line)?'note-item':'note-paragraph',text:line.replace(/^#{1,6}\s+/,'').replace(/^\s*[-*]\s+/,'').replace(/\*\*|`/g,'')})); }
watchEffect(()=>applyPageSeo({title:en.value?'PCL Nexa — Changelog':'PCL Nexa — 更新日志',description:en.value?'Read the published release notes for PCL Nexa 2.0.':'查看 PCL Nexa 2.0 的发布记录、更新内容和改进。',path:'/changelog'}));
</script>
<style scoped>
.changes-main{max-width:1000px;padding-bottom:90px}.changes-toolbar{display:flex;justify-content:space-between;border-bottom:1px solid var(--market-border);padding:12px 0 25px;gap:20px;font-size:15px}.release-entry{display:grid;grid-template-columns:220px minmax(0,1fr);gap:60px;padding:55px 0;border-bottom:1px solid var(--market-border)}.release-entry header{display:flex;align-items:flex-start;flex-direction:column;gap:18px}.release-entry h2{font-size:26px;overflow-wrap:anywhere}.release-entry time{font-size:14px;color:var(--market-muted)}.release-entry header>a{font-size:14px}.release-source{color:var(--market-muted);font-size:14px;margin-bottom:22px}.release-body{overflow-wrap:anywhere}.note-heading{font-size:21px;font-weight:600;margin:26px 0 18px}.note-item{position:relative;padding-left:18px;margin:12px 0;line-height:1.85}.note-item:before{content:'•';position:absolute;left:0;color:var(--market-muted)}.note-paragraph{margin:12px 0;line-height:1.85}.load-message{padding:50px 0;color:var(--market-muted)}@media(max-width:700px){.release-entry{grid-template-columns:1fr;gap:24px;padding:35px 0}.release-entry header{gap:10px}.changes-main{padding-bottom:50px}}
</style>
