<template>
  <section class="runs" :aria-busy="loading">
    <header><div><h2>单次游戏运行</h2><p>把启动环境、资源占用和设置变化放在一起看。</p></div><el-button :loading="loading" @click="selected ? open(selected) : load()">刷新</el-button></header>
    <el-alert v-if="error" :title="error" type="error" :closable="false" />
    <template v-if="!selected">
      <el-empty v-if="!loading && !runs.length" description="尚未收到运行样本。需要更新后的客户端，并启用诊断信息。" />
      <button v-for="run in runs" :key="run.run" class="run-row" @click="open(run.run)"><span><b>{{ run.version }} · {{ run.os }}</b><small>{{ run.day }} · {{ run.run.slice(0,8) }}</small></span><span>{{ (run.elapsed/60000).toFixed(1) }} 分钟<small>{{ run.ended ? '已收到退出样本' : '尚未收到退出样本' }} · {{ run.samples }} 个窗口</small></span><span aria-hidden="true">→</span></button>
      <p class="note">显示筛选范围内最近 100 次运行。每次运行使用独立随机标识，不关联设备或账户。</p>
    </template>
    <template v-else>
      <el-button text @click="close">← 返回运行列表</el-button>
      <div class="overview"><article><small>加载器</small><strong>{{ first?.loader ?? inventory[0]?.loader ?? '—' }}</strong><span>{{ inventory[0]?.loader_version ?? '版本尚未收到' }}</span></article><article><small>Java / 堆内存配置</small><strong>{{ first?.java ?? '—' }}</strong><span>{{ number(first?.heap,'MiB') }}</span></article><article><small>模组清单</small><strong>{{ mods.length }} 项</strong><span>{{ inventoryComplete ? '已收到完整清单' : '未完整识别或仍有缺页' }}</span></article></div>
      <h3>启动环境</h3><p>Minecraft {{ inventory[0]?.game ?? '未识别' }} · {{ first?.classpath ?? '—' }} 个类路径条目</p><div class="components"><span v-for="(build,name) in components" :key="name">{{ name }} {{ build }}</span></div><p class="note">组件版本来自安装记录与解析后的版本元数据。未识别的值保持未知。</p>
      <h3>运行中的工作集</h3><svg viewBox="0 0 600 190" role="img" aria-label="按运行时间排列的工作集均值"><polyline v-for="(segment,i) in chartSegments" :key="i" :points="segment" fill="none" stroke="var(--el-color-primary)" stroke-width="2.5" /></svg>
      <div class="chart-axis"><span>0 分钟</span><span>工作集峰值 {{ number(Math.max(-1,...samples.map(p=>Number(p.peak))),'MiB') }}</span><span>{{ (Number(samples[samples.length-1]?.elapsed??0)/60000).toFixed(1) }} 分钟</span></div>
      <p class="note">30 秒一个采样窗口，CPU 按整机逻辑核心归一化。采样中断处不连线；没有退出样本不等于仍在运行。私有内存不是 JVM Native 或系统 Commit。</p>
      <h3>持久化设置与占用变化</h3><p class="note">设置每 30 秒检查一次。下表比较已保存设置对应窗口的均值，不证明游戏即时应用，也不证明因果关系。</p>
      <el-table :data="epochs" max-height="420"><el-table-column prop="epoch" label="阶段" width="65"/><el-table-column label="设置" min-width="230"><template #default="{row}">{{ settingsLabel(row.first) }}</template></el-table-column><el-table-column label="工作集均值" width="130"><template #default="{row}">{{ number(row.mean,'MiB') }}</template></el-table-column><el-table-column label="较前一阶段" width="130"><template #default="{row}">{{ row.delta === null ? '—' : `${row.delta > 0 ? '+' : ''}${row.delta.toFixed(1)} MiB` }}</template></el-table-column><el-table-column prop="count" label="有效采样" width="95" /></el-table>
      <h3>资源样本</h3><el-table :data="samples" max-height="360"><el-table-column label="运行时间" width="100"><template #default="{row}">{{ (Number(row.elapsed)/60000).toFixed(1) }} 分</template></el-table-column><el-table-column label="工作集均值"><template #default="{row}">{{ number(row.working,'MiB') }}</template></el-table-column><el-table-column label="工作集峰值"><template #default="{row}">{{ number(row.peak,'MiB') }}</template></el-table-column><el-table-column label="私有内存"><template #default="{row}">{{ number(row.private,'MiB') }}</template></el-table-column><el-table-column label="CPU"><template #default="{row}">{{ number(row.cpu,'%') }}</template></el-table-column></el-table>
      <el-button v-if="next !== null" :loading="loading" @click="open(selected,true)">加载后续样本</el-button>
      <h3>模组元数据</h3><el-input v-model="search" clearable placeholder="搜索模组 ID" aria-label="搜索模组"/><el-table :data="filteredMods" max-height="460"><el-table-column prop="id" label="模组 ID" min-width="150"/><el-table-column prop="version" label="版本" min-width="120"/><el-table-column label="状态" width="90"><template #default="{row}">{{ row.enabled ? '已启用' : '已禁用' }}</template></el-table-column><el-table-column prop="format" label="证据来源" min-width="160"/><el-table-column label="声明依赖" min-width="230"><template #default="{row}"><div v-for="(range,id) in row.dependencies" :key="id">{{ id }} {{ range }}</div><small v-if="!row.complete">依赖信息仅部分解析</small></template></el-table-column></el-table>
      <p class="note">元数据来自模组声明，不等于运行时已加载或兼容性已验证。未识别文件：{{ inventory[0]?.unknown ?? '未知' }}。</p>
    </template>
  </section>
</template>
<script setup lang="ts">
import {computed,onUnmounted,ref,watch} from 'vue';
import {pluginCenterApi} from '@/api/pluginCenter';
const props=defineProps<{days:number;version:string;os:string}>();
const runs=ref<Awaited<ReturnType<typeof pluginCenterApi.launcherRuns>>['runs']>([]),selected=ref(''),samples=ref<Record<string,string>[]>([]),inventory=ref<Record<string,string>[]>([]),next=ref<number|null>(null),loading=ref(false),error=ref(''),search=ref('');let generation=0;
async function load(){const id=++generation;loading.value=true;error.value='';try{const result=await pluginCenterApi.launcherRuns(props.days,props.version,props.os);if(id===generation)runs.value=result.runs;}catch{if(id===generation)error.value='无法加载运行数据，请稍后重试。';}finally{if(id===generation)loading.value=false;}}
async function open(run:string,append=false){const id=++generation;selected.value=run;loading.value=true;error.value='';if(!append){samples.value=[];inventory.value=[];next.value=null;}try{const result=await pluginCenterApi.launcherRun(run,append?next.value??-1:-1);if(id!==generation)return;samples.value=append?[...samples.value,...result.samples]:result.samples;inventory.value=result.mods;next.value=result.next;}catch{if(id===generation)error.value='无法读取本次运行，请重试。';}finally{if(id===generation)loading.value=false;}}
function close(){generation++;selected.value='';loading.value=false;}
const first=computed(()=>samples.value[0]);
const components=computed(()=>{try{return JSON.parse(inventory.value[0]?.components??'{}') as Record<string,string>;}catch{return {};}});
type Mod={id:string;version:string;format:string;enabled:boolean;complete:boolean;dependencies:Record<string,string>};
const mods=computed(()=>inventory.value.flatMap(p=>{try{return JSON.parse(p.mods) as Mod[];}catch{return [];}})),filteredMods=computed(()=>mods.value.filter(m=>m.id.toLowerCase().includes(search.value.toLowerCase())));
const inventoryComplete=computed(()=>inventory.value.length>0&&inventory.value.every(p=>p.complete==='1'&&Number(p.unknown)===0)&&inventory.value.length===Number(inventory.value[0].pages));
function number(value:string|number|undefined,unit:string){return value===undefined||!Number.isFinite(Number(value))||Number(value)<0?'未采集':`${Number(value).toFixed(1)} ${unit}`;}
function settingsLabel(p:Record<string,string>){return `视距 ${number(p.render,'区块')} · 模拟 ${number(p.simulation,'区块')} · 帧率 ${number(p.fps,'FPS')} · 画质 ${p.graphics==='0'?'流畅':p.graphics==='1'?'高品质':p.graphics==='2'?'极佳':'未知'} · 垂直同步 ${p.vsync==='1'?'开':p.vsync==='0'?'关':'未知'}`;}
const epochs=computed(()=>{const groups=new Map<string,Record<string,string>[]>();for(const sample of samples.value){const list=groups.get(sample.epoch)??[];list.push(sample);groups.set(sample.epoch,list);}let previous:number|null=null;return [...groups].map(([epoch,rows])=>{const valid=rows.filter(r=>Number(r.working)>=0&&Number(r.samples)>0),count=valid.reduce((n,r)=>n+Number(r.samples),0),mean=count?valid.reduce((n,r)=>n+Number(r.working)*Number(r.samples),0)/count:-1,delta=previous!==null&&mean>=0?mean-previous:null;previous=mean<0?null:mean;return{epoch,first:rows[0],count,mean,delta};});});
const chartSegments=computed(()=>{const last=Math.max(1,...samples.value.map(p=>Number(p.elapsed))),peak=Math.max(1,...samples.value.map(p=>Number(p.working)));const segments:string[][]=[];let previous=-2;for(const p of samples.value){if(Number(p.working)<0){previous=-2;continue;}if(Number(p.sequence)!==previous+1)segments.push([]);segments[segments.length-1].push(`${10+Number(p.elapsed)/last*580},${175-Number(p.working)/peak*160}`);previous=Number(p.sequence);}return segments.map(s=>s.join(' '));});
watch(()=>[props.days,props.version,props.os],()=>{close();void load();},{immediate:true});onUnmounted(()=>generation++);
</script>
<style scoped>
.chart-axis{display:flex;justify-content:space-between;gap:1rem;color:var(--el-text-color-secondary);font-size:.8rem;margin-top:.5rem}.components{display:flex;gap:1rem;flex-wrap:wrap}.runs{padding:1.5rem;border:1px solid var(--el-border-color-lighter);border-radius:1.4rem;background:var(--el-bg-color);color:var(--el-text-color-primary)}header,.run-row{display:flex;align-items:center;justify-content:space-between;gap:1rem}h2{margin:0;font-size:1.4rem}h3{margin:2rem 0 1rem}p,small,.note{color:var(--el-text-color-secondary)}.run-row{width:100%;padding:1.1rem 0;border:0;border-bottom:1px solid var(--el-border-color-lighter);background:none;color:inherit;text-align:left;cursor:pointer}.run-row:hover{color:var(--el-color-primary)}.run-row:active{opacity:.65}.run-row span:first-child{flex:1}small{display:block;margin-top:.25rem}.overview{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin:1.5rem 0}.overview article{display:grid;gap:.5rem;padding:1.2rem;background:var(--el-fill-color-light);border-radius:1rem}.overview strong{font-size:1.6rem}.note{font-size:.8rem;line-height:1.7}svg{width:100%;max-height:230px;background:var(--el-fill-color-light);border-radius:1rem}@media(max-width:700px){.overview{grid-template-columns:1fr}.runs{padding:1rem}.run-row{flex-wrap:wrap}}
</style>
